name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main # デフォルトブランチ
    tags:
      - "v*"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. コードをチェックアウト
      - uses: actions/checkout@v4

      # 2. Node.js セットアップ
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # 3. ディレクトリ確認（デバッグ用）
      - run: ls -la

      # 4. 依存関係インストール
      - run: npm ci

      # 5. ビルド
      - run: npm run build

      # 6. 404.html をコピー
      - run: cp dist/index.html dist/404.html

      # 7. GitHub Pages にアップロード
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      # 8. デプロイ
      - id: deploy
        uses: actions/deploy-pages@v4
