name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to deploy"
        required: false
        default: ""

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: ls -la
      - run: npm ci
      - run: npm run build
      - run: cp dist/index.html dist/404.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - id: deploy
        uses: actions/deploy-pages@v4
